### PR TITLE
Implement Panama.SqlServer.Dapper SqlServerQuery as SqlServerDialect IQuery(Async)

### PR DESCRIPTION
**Pull request by oneEyedSunday**

### CODE REVIEW

**Comment by diraniac** [comment]
this pull request can be closed, I added SqlQueryAsync on master without realizing you did it here first - my apologies @oneEyedSunday

**Comment by diraniac** [comment]
also, there was an existing `Panama.Sql.Dapper` project in `Panama.Core` where I made the updates: https://github.com/mrogunlana/Panama.Core/tree/master/Panama.Sql.Dapper

**Comment by oneEyedSunday** [comment]
;)

**Comment by mrogunlana** [comment]
closing in favor of new `v6` framework

**Pull request closed without merging**
